### ISSUE TITLE
Typo in deep copy post

### ISSUE THREAD

**Issue by doodlewind** [sunshine940326/sunshine940326.github.io#3]
Hi, this blog looks good and pretty well maintained!

A minor typo is found here:
https://github.com/sunshine940326/sunshine940326.github.io/blob/Hexo/source/_posts/deepcopy.md

In its title, `ECAMScript` -> `ECMAScript`

Feel free to close this issue if it disturbs :-)

**Comment by sunshine940326** [comment]
thanks
